esphome:
  name: pcf-io-expander-test
  friendly_name: pcf_io_expander_test

  project:
    name: "MaJerle.my-first-project"
    version: "0.0.3"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  # Spawn the AP with no credentials
  ap: {}

captive_portal:

dashboard_import:
  package_import_url: github://MaJerle/esphome-io-boards/esp32-8in-8out-relay-eth-v0.1.yaml
  import_full_config: false

# Simple web server goes here
web_server:
  port: 80

# I2C configuration
i2c:
  sda: GPIO05
  scl: GPIO16
  scan: true
  id: bus_main

# PFC expanders
pcf8574:
  - id: "pcf8574_hub_input"
    address: 0x26
    pcf8575: false

packages:
  channel_1: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 1
      pcf_input_channel_number: 0
      switch_output_id: GPIO04
  channel_2: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 2
      pcf_input_channel_number: 1
      switch_output_id: GPIO02
  channel_3: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 3
      pcf_input_channel_number: 2
      switch_output_id: GPIO15
  channel_4: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 4
      pcf_input_channel_number: 3
      switch_output_id: GPIO13
  channel_5: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 5
      pcf_input_channel_number: 4
      switch_output_id: GPIO12
  channel_6: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 6
      pcf_input_channel_number: 5
      switch_output_id: GPIO14
  channel_7: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 7
      pcf_input_channel_number: 6
      switch_output_id: GPIO32
  channel_8: !include
    file: esp32-8in-8out-relay-eth-v0.1-channel.yaml
    vars:
      id: 8
      pcf_input_channel_number: 7
      switch_output_id: GPIO33

# Button list
button:
  - platform: restart
    name: "Restart"
  - platform: factory_reset
    name: "Factory reset"

# Example configuration entry
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
      address_3:
        name: ESP IP Address 3
      address_4:
        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address

# List of sensors
sensor:
  - platform: uptime
    type: seconds
    name: "Uptime"
